---
version: "3.1"

volumes: 
  portainer_data:

networks:
  front:

services:
  server:
    image: portainer/portainer-ce:2.11.0-alpine
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - 8000:8000
      - 9000:9000
      - 9443:9443
    networks:
      - front
    healthcheck:
      test: wget --no-verbose --no-check-certificate --tries=1 --spider https://localhost:9443
      interval: 30s
      retries: 5
      start_period: 5s
      timeout: 10s

